/**
 * Hint Service Types
 *
 * Core type definitions for the enhanced hint generation system.
 */

import type { InteractionEvent, InstructionalUnit, SQLProblem, RetrievedChunkInfo } from '../../types';
import type { SqlEngageRecord } from '../../data/sql-engage';
import type { GuidanceRung } from '../guidance-ladder';
import type { RetrievalBundle } from '../content/retrieval-bundle';

/**
 * Available resource types for hint generation
 */
export type AvailableResources = {
  /** SQL-Engage CSV dataset is always available */
  sqlEngage: boolean;
  /** Textbook has saved units for this learner */
  textbook: boolean;
  /** LLM service is reachable */
  llm: boolean;
  /** PDF index is loaded */
  pdfIndex: boolean;
};

/**
 * Enhanced hint with metadata about sources used
 */
export type EnhancedHint = {
  /** The hint content */
  content: string;
  /** Which rung this hint belongs to */
  rung: GuidanceRung;
  /** Sources that contributed to this hint */
  sources: {
    sqlEngage: boolean;
    textbook: boolean;
    llm: boolean;
    pdfPassages: boolean;
  };
  /** Concept IDs referenced */
  conceptIds: string[];
  /** Source reference IDs (for rung 2+) */
  sourceRefIds?: string[];
  /** Textbook units referenced (if available) */
  textbookUnits?: InstructionalUnit[];
  /** Whether this was generated by LLM */
  llmGenerated: boolean;
  /** Confidence score (0-1) based on source richness */
  confidence: number;
  /** Retrieval confidence used for safety gating */
  retrievalConfidence: number;
  /** Why fallback mode was used (if applicable) */
  fallbackReason?: string | null;
  /** Whether safety filtering was applied to hint content */
  safetyFilterApplied: boolean;
  /** Source IDs used for retrieval traceability */
  retrievedSourceIds: string[];
  /** Chunk IDs used for retrieval traceability */
  retrievedChunkIds: string[];
  /** Whether LLM was requested but failed (for UI feedback) */
  llmFailed?: boolean;
  /** Error message if LLM failed */
  llmErrorMessage?: string;
};

/**
 * Options for hint generation
 */
export type HintGenerationOptions = {
  /** Learner ID */
  learnerId: string;
  /** Problem ID */
  problemId: string;
  /** Session ID (optional) */
  sessionId?: string;
  /** Current error subtype */
  errorSubtypeId?: string;
  /** Target rung level */
  rung: GuidanceRung;
  /** Recent interactions for context */
  recentInteractions: InteractionEvent[];
  /** Whether to force LLM generation even if available */
  forceLLM?: boolean;
};

/**
 * Derived learner state for adaptive generation.
 * Internal-only context used to keep hints tied to recent errors/retries.
 */
export type LearningSignalSummary = {
  /** Most recent error or incorrect-result signal */
  latestIssue: string;
  /** Count of failed executions/errors for this problem/session */
  failedRunCount: number;
  /** Retry count inferred from failures and retrieval trace */
  retryCount: number;
  /** Hints already viewed for this problem/session */
  hintCount: number;
  /** Recent interaction event types in order */
  lastInteractionTypes: string[];
  /** Why the learner may be stuck */
  stuckReason?: string;
};

/**
 * Context for adaptive hint generation
 * Passed to generateAdaptiveHint for creating pedagogically progressive hints
 */
export type AdaptiveHintContext = {
  /** Current rung level (1, 2, or 3) */
  rung: 1 | 2 | 3;
  /** Error subtype identifier */
  errorSubtype: string;
  /** Current problem information */
  problem: SQLProblem;
  /** Array of hints already given to the learner */
  previousHints: string[];
  /** Relevant textbook content */
  textbookUnits: InstructionalUnit[];
  /** Relevant PDF passages */
  pdfPassages: RetrievedChunkInfo[];
  /** SQL-Engage records for this error subtype */
  sqlEngageRecords: SqlEngageRecord[];
  /** Derived learner state from recent interactions and retrieval trace */
  learningSignals: LearningSignalSummary;
};

/**
 * Parsed LLM output for adaptive hints
 */
export type AdaptiveHintOutput = {
  content: string;
  conceptIds: string[];
  sourceRefIds: string[];
};

/**
 * Internal: Retrieval signal metadata
 */
export type RetrievalSignalMeta = {
  retrievalConfidence: number;
  retrievedSourceIds: string[];
  retrievedChunkIds: string[];
};

/**
 * Internal: Refined hint resolution result
 */
export type RefinedHintResolution =
  | {
      content: string;
      sourceChunkIds: string[];
      refinementModel?: string;
      refinementConfidence?: number;
    }
  | {
      content: null;
      rejectReason?: string;
    };

/**
 * Safety layer result
 */
export type SafetyLayerResult = {
  content: string;
  safetyFilterApplied: boolean;
  fallbackReason: string | null;
};

/**
 * Scored hint candidate result
 */
export type ScoredHintCandidate = {
  accepted: boolean;
  content: string;
  fallbackReason: string | null;
  safetyFilterApplied: boolean;
};

/**
 * Extended retrieval bundle with textbook units
 */
export type EnhancedRetrievalBundle = RetrievalBundle & {
  textbookUnits?: InstructionalUnit[];
};

/** Minimum retrieval confidence threshold */
export const MIN_RETRIEVAL_CONFIDENCE = 0.45;

/** Service version identifier */
export const ENHANCED_HINT_SERVICE_VERSION = 'enhanced-hint-v2.1.0-modular';
